### ISSUE TITLE
How to run run_test_cuhk.sh

### ISSUE THREAD

**Issue by mufasachan** [JialeCao001/PSTR#2]
Hello, 

First, thanks for sharing the code of your work and congratulations for your CVPR acceptance! 

I am sorry if my question looks dumb but I cannot figure out how to run `run_test_cuhk.sh`. I added the log at the bottom of my issue. It seems so that I should fill the working directory - I took the same as you `$ROOT/work_dirs` - with the pstr_results.plk. 
I do not understand why I should compute the detection since PSTR aims to compute detection and ReID features "in one shot", kind of. From what I understood, the point of PSTR is to compute detections and reid features so I cannot understand why I should provide detections.  

Plus, it does not seem that `PartAttention` is part of the `attention` Registry.

My packages versions are: 

- mmcv-full: 1.3.17
- mmdet: 2.18.1
- torch: 1.8.0
- torchvision: 0.9.0

And CUDA is 11.1 (minimal version for my GPU).

If you need anymore information, let me know :smiley:. 

Best regards,
Mathias.

---

```
loading annotations into memory...
Done (t=0.13s)
creating index...
index created!
3
/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py:341: UserWarning: The arguments `feedforward_channels` in BaseTransformerLayer has been deprecated, now you should set `feedforward_channels` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py:341: UserWarning: The arguments `ffn_dropout` in BaseTransformerLayer has been deprecated, now you should set `ffn_drop` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py:341: UserWarning: The arguments `ffn_num_fcs` in BaseTransformerLayer has been deprecated, now you should set `num_fcs` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py:92: UserWarning: The arguments `dropout` in MultiheadAttention has been deprecated, now you can separately set `attn_drop`(float), proj_drop(float), and `dropout_layer`(dict) 
  warnings.warn('The arguments `dropout` in MultiheadAttention '
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/utils/transformer.py", line 439, in __init__
    super(DetrTransformerDecoderLayer, self).__init__(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 382, in __init__
    attention = build_attention(attn_cfgs[index])
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 40, in build_attention
    return build_from_cfg(cfg, ATTENTION, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'PartAttention is not in the attention registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/utils/transformer.py", line 639, in __init__
    super(DeformableDetrTransformerDecoder, self).__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 545, in __init__
    self.layers.append(build_transformer_layer(transformerlayers[i]))
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 50, in build_transformer_layer
    return build_from_cfg(cfg, TRANSFORMER_LAYER, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "DetrTransformerDecoderLayer: 'PartAttention is not in the attention registry'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/utils/transformer.py", line 1076, in __init__
    super(PstrTransformer, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/utils/transformer.py", line 566, in __init__
    self.decoder1 = build_transformer_layer_sequence(decoder1)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 55, in build_transformer_layer_sequence
    return build_from_cfg(cfg, TRANSFORMER_LAYER_SEQUENCE, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'DeformableDetrTransformerDecoder: "DetrTransformerDecoderLayer: \'PartAttention is not in the attention registry\'"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/pstr_head.py", line 56, in __init__
    super(PSTRHead, self).__init__(
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/detr_reid_head.py", line 143, in __init__
    self.transformer = build_transformer(transformer)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/utils/builder.py", line 11, in build_transformer
    return build_from_cfg(cfg, TRANSFORMER, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'PstrTransformer: \'DeformableDetrTransformerDecoder: "DetrTransformerDecoderLayer: \\\'PartAttention is not in the attention registry\\\'"\''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/pstr.py", line 10, in __init__
    super(DETRReID, self).__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage_reid.py", line 37, in __init__
    self.bbox_head = build_head(bbox_head)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/builder.py", line 40, in build_head
    return HEADS.build(cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'PSTRHead: \'PstrTransformer: \\\'DeformableDetrTransformerDecoder: "DetrTransformerDecoderLayer: \\\\\\\'PartAttention is not in the attention registry\\\\\\\'"\\\'\''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 234, in <module>
    main()
  File "./tools/test.py", line 183, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'PSTR: \'PSTRHead: \\\'PstrTransformer: \\\\\\\'DeformableDetrTransformerDecoder: "DetrTransformerDecoderLayer: \\\\\\\\\\\\\\\'PartAttention is not in the attention registry\\\\\\\\\\\\\\\'"\\\\\\\'\\\'\''
------------------------
Traceback (most recent call last):
  File "./tools/test_results_cuhk.py", line 75, in <module>
    with open(results_path, 'rb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/pstr_results.pkl'
Traceback (most recent call last):
  File "./tools/test_results_cuhk_cbgm.py", line 76, in <module>
    with open(results_path, 'rb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/pstr_results.pkl'
```

**Comment by JialeCao001** [comment]
@mufasachan Thanks for your interest. Please compile mmcv provided in our PSTR to solve the issue of no registry. The pkl file contains the results of both detection and re-id features. The reason why we provide the pkl file is that ./tools/test_results_prw.py needs to read both detection and re-id features from this path. This is just for performance evaluation, not for inference.

**Comment by Ricelll** [comment]
@mufasachan hello, could u tell me how to compiled mmcv to get pstr_results.pkl?
i have installed mmcv, but it occured to get this question that "No such file or directory: 'work_dirs/pstr_results.pkl'"
thank u very much!
